#!/usr/bin/env bash

# Prevent sudo
#https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo-linux.md
export NPM_PACKAGES="$HOME/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

export PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath`
# command
unset MANPATH  # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"


# Add local npm binaries to path.
export PATH="./node_modules/.bin:$PATH"
